apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvcache-worker
  namespace: kvcache-serve
  labels:
    app: kvcache-worker
spec:
  replicas: 3

  selector:
    matchLabels:
      app: kvcache-worker

  template:
    metadata:
      labels:
        app: kvcache-worker

    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: worker
          image: kvcache-serve:local
          imagePullPolicy: Never

          command:
            - python
            - -m
            - app.worker

          env:
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          envFrom:
            - configMapRef:
                name: kvcache-config

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
